HTTP_PORT: int = 80
HTTPS_PORT: int = 443
HTTP_SUCCESS_CODE: str = "200"
DEFAULT_BUFFER_SIZE: int = 4096
HTTP_VERSION: str = "HTTP/1.0"
USER_AGENT: str = "Python/WeatherCrawler/0.0001"

LOG_PREFIXES: str = "[LOG]: "
WARNING_PREFIXES: str = "[WARNING]: "
ERROR_PREFIXES: str = "[ERROR]: "